### ISSUE TITLE
Add support for client cert authentication

### ISSUE THREAD

**Issue by lulf** [drogue-iot/embedded-tls#14]
Add support for supplying client certificate and send to server for authenticating client.

**Comment by overheat** [comment]
Any progress on this enhancement? Thanks.

**Comment by lulf** [comment]
I think it is somewhat implemented but not tested, and iirc it didn't work fully last time I tested it manually, but I didn't have the time to debug it.

**Comment by overheat** [comment]
Could you share the manually testing steps?
I can try to finger it out.

**Comment by lulf** [comment]
I think the following steps should work assuming you use pem_parser dependency.

````
    let pem = include_str!("client-cert.pem");
    let der = pem_parser::pem_to_der(pem);
    let config = TlsConfig::new().with_server_name("localhost").with_cert(Certificate::X509(&der[...]));
````

I think if you can modify `tests/client_test.rs` with a test case using client cert authentication, that would be awesome.
