### ISSUE TITLE
The atomic-polyfill crate is deprecated.

### ISSUE THREAD

**Issue by kefran06** [drogue-iot/embedded-tls#140]
The atomic-polyfill crates is deprecated and it is recommended that the portable-atomic crate be used instead.
(https://github.com/embassy-rs/atomic-polyfill)
Is it possible to change to use the portable-atomic crate?

※ Currently, on the xtensa-esp32-espidf target, the atomic-polyfill causes a compile error. 

error[E0432]: unresolved import `core::sync::atomic::AtomicU64`

**Comment by lulf** [comment]
Yeah, that sounds good. Would you like to open a PR for it?
